REGION_MAP = {

    # A trier - ajout temp
    'Hunua Ranges':         'Auckland',
    'Hawkes Bay Airport':   'Hawkes Bay',
    'Arthurs Pass':         'Canterbury',

    # Nationales
    'all':                  'all',
    'New Zealand':          'all',
    'North Island':         'all',
    'South Island':         'all',

    # Northland
    'Northland':            'Northland',
    'Whangarei':            'Northland',
    'Kaitaia':              'Northland',
    'Kawakawa':             'Northland',
    'Wairua Falls':         'Northland',
    'Haruru':               'Northland',
    'Tutukaka Harbour':     'Northland',
    'Cape Reinga':          'Northland',
    'Horeke':               'Northland',
    'Puhipuhi':             'Northland',

    # Auckland
    'Auckland':             'Auckland',
    'Auckland City':        'Auckland',
    'Kohimarama':           'Auckland',
    'New Lynn':             'Auckland',
    'Waiheke Island':       'Auckland',
    'Clevedon':             'Auckland',
    'Papatoetoe':           'Auckland',
    'Stanmore Bay':         'Auckland',
    'Algies Bay':           'Auckland',

    # Waikato
    'Waikato':              'Waikato',
    'Hamilton':             'Waikato',
    'Raglan':               'Waikato',
    'Thames':               'Waikato',
    'Coromandel':           'Waikato',
    'Coromandel Peninsula': 'Waikato',
    'Whangamata':           'Waikato',
    'Kaiaua':               'Waikato',
    'Waihi Beach':          'Waikato',
    'Hikuai':               'Waikato',

    # Bay of Plenty
    'Bay of Plenty':        'Bay of Plenty',
    'Tauranga':             'Bay of Plenty',
    'Mount Maunganui':      'Bay of Plenty',
    'Edgecumbe':            'Bay of Plenty',
    'Rotorua':              'Bay of Plenty',
    'Whitianga':            'Bay of Plenty',

    # Gisborne
    'Gisborne':             'Gisborne',
    'Gisborne City':        'Gisborne',
    'Tokomaru Bay':         'Gisborne',
    'Tolaga_Bay':           'Gisborne',
    'Mahia':                'Gisborne',

    # Hawkes Bay ← sans apostrophe, correspond au split
    "Hawke's Bay":          'Hawkes Bay',
    "Hawkes Bay":           'Hawkes Bay',
    "Hawke's Bay Airport":  'Hawkes Bay',
    'Napier':               'Hawkes Bay',
    'Te Pohue':             'Hawkes Bay',
    'Te Haroto':            'Hawkes Bay',

    # Taranaki
    'Taranaki':             'Taranaki',
    'New Plymouth':         'Taranaki',
    'Rahotu':               'Taranaki',

    # Manawatu-Wanganui ← avec un seul 'h', correspond au split
    'Manawatu-Wanganui':    'Manawatu-Wanganui',
    'Manawatu-Whanganui':   'Manawatu-Wanganui',
    'Whanganui':            'Manawatu-Wanganui',
    'Wanganui':             'Manawatu-Wanganui',
    'Pipiriki':             'Manawatu-Wanganui',
    'Marton':               'Manawatu-Wanganui',
    'Koitiata':             'Manawatu-Wanganui',
    'Waitotara':            'Manawatu-Wanganui',
    'Whangaehu':            'Manawatu-Wanganui',
    'Levin':                'Manawatu-Wanganui',
    'Palmerston North':     'Manawatu-Wanganui',
    'Desert Road':          'Manawatu-Wanganui',
    'Waiouru':              'Manawatu-Wanganui',
    'National Park':        'Manawatu-Wanganui',
    'Mount Ruapehu':        'Manawatu-Wanganui',
    'Ohakune':              'Manawatu-Wanganui',

    # Wellington
    'Wellington':           'Wellington',
    'Wellington City':      'Wellington',
    'Wellington Airport':   'Wellington',
    'Hutt Valley':          'Wellington',
    'Lower Hutt':           'Wellington',
    'Evans Bay':            'Wellington',
    'Wainuimata Hill':      'Wellington',
    'Paraparaumu':          'Wellington',
    'Paekakariki':          'Wellington',
    'Petone':               'Wellington',
    'Wairarapa':            'Wellington',
    'Rimutaka Hill':        'Wellington',
    'Masterton':            'Wellington',
    'Martinborough':        'Wellington',
    'Baring Head':          'Wellington',
    'Cook Strait':          'Wellington',

    # Nelson/Marlborough ← région fusionnée, couvre Tasman + Nelson + Marlborough
    'Nelson':               'Nelson/Marlborough',
    'Stoke':                'Nelson/Marlborough',
    'Richmond':             'Nelson/Marlborough',
    'Cable Bay':            'Nelson/Marlborough',
    'Monaco':               'Nelson/Marlborough',
    'Tasman':               'Nelson/Marlborough',
    'Tasman_Nelson':        'Nelson/Marlborough',
    'Tasman-Nelson':        'Nelson/Marlborough',
    'Golden Bay':           'Nelson/Marlborough',
    'Takaka':               'Nelson/Marlborough',
    'Takaka Hill':          'Nelson/Marlborough',
    'Kaiteriteri':          'Nelson/Marlborough',
    'Motueka':              'Nelson/Marlborough',
    'Riwaka':               'Nelson/Marlborough',
    'Marlborough':          'Nelson/Marlborough',
    'Blenheim':             'Nelson/Marlborough',
    'Picton':               'Nelson/Marlborough',
    'Linkwater':            'Nelson/Marlborough',
    'Kaikoura':             'Nelson/Marlborough',

    # West Coast
    'West Coast':           'West Coast',
    'Westland':             'West Coast',
    'Hokitika':             'West Coast',
    'Franz Josef':          'West Coast',
    'Fox Glacier':          'West Coast',
    'Westport':             'West Coast',
    'Greymouth':            'West Coast',
    'Whataroa':             'West Coast',
    'Springs Junction':     'West Coast',
    'Haast':                'West Coast',
    'Waiho Bridge':         'West Coast',
    'Arahura River':        'West Coast',
    'Cropp River':          'West Coast',
    'Goat Creek':           'West Coast',
    'Haupiri River':        'West Coast',
    'Hari Hari':            'West Coast',
    'Karamea':              'West Coast',
    'Granity':              'West Coast',

    # Canterbury
    'Canterbury':           'Canterbury',
    'Canterbury (South)':   'Canterbury',
    'Christchurch':         'Canterbury',
    'Rangiora':             'Canterbury',
    'Ashburton':            'Canterbury',
    'Akaroa':               'Canterbury',
    'Port Hills':           'Canterbury',
    'Lyttleton':            'Canterbury',
    'Mt Somers':            'Canterbury',
    'Mt Hutt':              'Canterbury',
    'Geraldine':            'Canterbury',
    'Leeston':              'Canterbury',
    'Ashley Forest':        'Canterbury',
    'Lewis Pass':           'Canterbury',
    "Arthur's Pass":        'Canterbury',
    'Fairlie':              'Canterbury',
    'Tekapo':               'Canterbury',
    'Timaru':               'Canterbury',
    'Hurunui District':     'Canterbury',
    'Selwyn':               'Canterbury',
    'Rangitata River':      'Canterbury',
    'St Andrews':           'Canterbury',

    # Otago
    'Otago':                'Otago',
    'Dunedin':              'Otago',
    'Dunedin City':         'Otago',
    'Oamaru':               'Otago',
    'Maniototo':            'Otago',
    'Clarks Junction':      'Otago',
    'Lawrence':             'Otago',
    'Naseby':               'Otago',
    'Otago Hill Country':   'Otago',
    'Maheno':               'Otago',
    'Five Forks':           'Otago',
    'Balclutha':            'Otago',
    'Mt Hercules':          'Otago',

    # Southland
    'Southland':            'Southland',
    'Invercargill':         'Southland',
    'Chatham Islands':      'Southland',
    'Gore':                 'Southland',
    'Mataura':              'Southland',
    'Fiordland':            'Southland',
    'Lumsden':              'Southland',
    'Howden Hut':           'Southland',
    'Milford Sound':        'Southland',
    'Hollyford':            'Southland',
}